#https://medium.com/@ramanamuttana/build-a-docker-image-using-maven-and-spring-boot-418e24c00776
# Use an official Maven image as the base image
FROM maven:4.0.0-rc-5-sapmachine-25 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the pom.xml and the project files to the container
COPY pom.xml .
COPY src ./src

# Build the application using Maven
RUN mvn clean package -DskipTests

# Set the working directory in the container
FROM openjdk:27-ea-slim-trixie

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file from the previous stage to the container
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
# Set the command to run the application
CMD ["java", "-jar", "app.jar"]