spring.application.name=backend
server.servlet.contextPath=/api
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

jwt.secret=${JWT_SECRET}
spring.mongodb.host=${SPRING_DATA_MONGODB_HOST}
spring.mongodb.port=${SPRING_DATA_MONGODB_PORT}
spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.mongodb.username=${SPRING_DATA_MONGODB_USERNAME}
spring.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD}
spring.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}